services:
  web:
    image: nginx:alpine
    container_name: nginx_btweb
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
      - ./nginx_conf:/etc/nginx/conf.d
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    container_name: nodered_btweb
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data
    restart: unless-stopped

  mariadb:
    image: mariadb:10.11
    container_name: mariadb_btweb
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: web_db
      MYSQL_USER: vinh
      MYSQL_PASSWORD: "123456"
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_btweb
    environment:
      PMA_HOST: mariadb
    ports:
      - "8081:80"
    depends_on:
      - mariadb
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared_btweb
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiNDhlMWU4MWUzY2MzOTcxNDlmMDg0MDk4OTU4YzUxNTUiLCJ0IjoiZWVhZmE2MDEtZTFkMi00YWNjLTliZWMtNzUxMmMxMDU1MDRjIiwicyI6Ik5UbGlNRE5tWlRVdE56bGpaaTAwWm1NMkxUZ3pOV010T1dJMk1qWmxaak5pTVdGayJ9
    restart: unless-stopped
