# Khối cấu hình cho Website số 1
server {
    listen 80;
    server_name web1.vinhirb.id.vn; # Khai báo chính xác domain 1

    # Đường dẫn trỏ tới thư mục code của web 1 bên trong Docker
    root /usr/share/nginx/html/site1;
    index index.html;
}

# Khối cấu hình cho Website số 2
server {
    listen 80;
    server_name web2.vinhirb.id.vn; # Khai báo chính xác domain 2

    # Đường dẫn trỏ tới thư mục code của web 2 bên trong Docker
    root /usr/share/nginx/html/site2;
    index index.html;
}
